#!/usr/bin/env bash

python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*DoubleScattering*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*WWW*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*WWZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*WZZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*ZZZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*WZTo2L2Q*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*WZTo3LNu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*Wg_MADGRAPHMLM*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*Zg*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*ZZTo2L2Nu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*ZZTo2L2Q*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*ZZTo4L*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*WpWpJJ_QCD*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*WpWpJJ_EWK*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*TTZjets*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*TTWjets*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*TTZToLLNuNu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*GluGluToWW*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*TTTo2L2Nu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*ST_s-channel*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*ST_t-channel_antitop*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*ST_t-channel_top*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*ST_tW_antitop*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*ST_tW_top*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv4_GTv16_Full2018v4/MCl1loose2018__MCCorr2018__l2loose__l2tightOR2018v4/nanoLatino_*DYJetsToLL_*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
echo "This is the END"


