#!/usr/bin/env bash

python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/data_2017 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Run2017_102X_nAODv4_Full2017v5/DATAl1loose2017v5__l2loose__l2tightOR2017v5/*SingleMuon*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleDataSingleMuon --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/data_2017 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Run2017_102X_nAODv4_Full2017v5/DATAl1loose2017v5__l2loose__l2tightOR2017v5/*SingleElectron*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleDataSingleElectron --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/data_2017 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Run2017_102X_nAODv4_Full2017v5/DATAl1loose2017v5__l2loose__l2tightOR2017v5/*DoubleEG*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleDataDoubleEG --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/data_2017 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Run2017_102X_nAODv4_Full2017v5/DATAl1loose2017v5__l2loose__l2tightOR2017v5/*MuonEG*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleDataMuonEG --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/data_2017 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Run2017_102X_nAODv4_Full2017v5/DATAl1loose2017v5__l2loose__l2tightOR2017v5/*DoubleMuon*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleDataDoubleMuon --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
echo "This is the END"
#jixiao@lxplus616:/afs/cern.ch/work/j/jixiao/nano/2016/CMSSW_10_2_13/src/PhysicsTools/NanoAODTools$
#nohup sh /afs/cern.ch/work/j/jixiao/nano/2016/CMSSW_10_2_13/src/PhysicsTools/NanoAODTools/python/postprocessing/chargeflip/skim0_data_2017.sh &> nohup_data2017.out&
#[1] 1264