#!/usr/bin/env bash


python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*DoubleScattering*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*WWW*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*WWZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*WZZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*ZZZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*WZTo2L2Q*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*WZTo3LNu_ext1*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*WZTo3LNu__part*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*Wg_MADGRAPHMLM*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*Zg*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*ZZTo2L2Nu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*ZZTo2L2Q*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*ZZTo4L*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
# python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*WpWpJJ_QCD*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
# python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*WpWpJJ_EWK*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*TTZjets*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*TTWJets*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*TTZToLLNuNu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*GluGluWWTo2L2Nu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*TTTo2L2Nu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*ST_s-channel*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*ST_t-channel_antitop*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*ST_t-channel_top*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*ST_tW_antitop*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*ST_tW_top*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v4/MCl1loose2016__MCCorr2016__l2loose__l2tightOR2016/nanoLatino_*DYJetsToLL_*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
echo "This is the END"


