#!/usr/bin/env bash
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*DYJetsToLL_M-105To160*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*DYJetsToLL_M-10to50*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*DYJetsToLL_M-50*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt


#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*DoubleScattering*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*WWW*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*WWZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*WZZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*ZZZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*WZTo2L2Q*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*WZTo3LNu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*Wg_MADGRAPHMLM*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*Zg*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*ZZTo2L2Nu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*ZZTo2L2Q*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*ZZTo4L*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*WpWpJJ_QCD*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*WpWpJJ_EWK__part*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*TTZjets*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*TTWjets*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*TTZToLLNuNu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*GluGluToWW*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*TTTo2L2Nu__part*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*ST_s-channel*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*ST_t-channel_antitop*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*ST_t-channel_top*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*ST_tW_antitop*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2018 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Autumn18_102X_nAODv5_Full2018v5/MCl1loose2018v5__MCCorr2018v5__l2loose__l2tightOR2018v5/nanoLatino_*ST_tW_top*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2018.txt --bo python/postprocessing/chargeflip/output_branch_selection_2018.txt
echo "This is the END"