#!/usr/bin/env bash
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*DYJetsToLL_M-105To160*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*DYJetsToLL_M-10to50*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*DYJetsToLL_M-50*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*DYJetsToLL_M-5to50*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*DYJetsToTT_MuEle_M-50*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt

#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*DoubleScattering*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*WWW*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*WWZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*WZZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*ZZZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*WZTo2L2Q*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*WZTo3LNu_ext1*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*WZTo3LNu_mllmin01*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*WZTo3LNu__part*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*Wg_MADGRAPHMLM*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*Zg*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*ZZTo2L2Nu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*ZZTo2L2Q_AMCNLOFXFX*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*ZZTo4L_AMCNLOFXFX*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*ZZTo4L__part*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*WpWpJJ_QCD*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*WpWpJJ_EWK*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*TTZjets*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*TTWJets*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*TTZToLLNuNu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*GluGluWWTo2L2Nu_MCFM*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*TTTo2L2Nu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*ST_s-channel*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*ST_t-channel_antitop*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*ST_t-channel_top*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*ST_tW_antitop*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
#python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2016 /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Summer16_102X_nAODv4_Full2016v5/MCl1loose2016v5__MCCorr2016v5__l2loose__l2tightOR2016v5/nanoLatino_*ST_tW_top*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleMC --bi python/postprocessing/chargeflip/keep_and_drop_2016.txt --bo python/postprocessing/chargeflip/output_branch_selection_2016.txt
echo "This is the END"