#!/usr/bin/env bash

python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*DoubleScattering*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*WWW*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*WWZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*WZZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*ZZZ*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*WZTo2L2Q*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*WZTo3LNu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*Wg_MADGRAPHMLM*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*Zg*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*ZZTo2L2Nu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*ZZTo2L2Q*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*ZZTo4L*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*WpWpJJ_QCD*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*WpWpJJ_EWK*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*TTZjets*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*TTWjets*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*TTZToLLNuNu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*GluGluToWW*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*TTTo2L2Nu*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*ST_s-channel*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*ST_t-channel_antitop*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*ST_t-channel_top*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*ST_tW_antitop*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*ST_tW_top*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*DYJetsToLL_*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
python scripts/nano_postproc.py /eos/user/j/jixiao/HWWNano/mc_2017/ /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWWNano/Fall2017_nAOD_v1_Full2017v2/MCl1loose2017v2__MCCorr2017__btagPerEvent__l2loose__l2tightOR2017/nanoLatino_*WWTo2L2Nu_PrivateNano*.root -I PhysicsTools.NanoAODTools.postprocessing.chargeflip.zcutModule zcutModuleConstr --bi python/postprocessing/chargeflip/keep_and_drop_2017.txt --bo python/postprocessing/chargeflip/output_branch_selection_2017.txt
echo "This is the END"
# nohup sh /afs/cern.ch/work/j/jixiao/nano/2016/CMSSW_10_2_13/src/PhysicsTools/NanoAODTools/python/postprocessing/chargeflip/skim0_mc_2017.sh &> nohup_mc2017.out&
# jixiao@lxplus605
